services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    stdin_open: true # docker run -i
    # volumes:
      # - .:/src
    ports:
      - 8000:8000
    command: bash